name: Docker
on: push

jobs:
  push:
    name: Build and Release Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Image Name
        run: |
          echo "IMAGE_ID=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.IMAGE_ID }}
          tags: |
            type=raw,value=dev

      - name: Build and push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_ID }}:dev
            ${{ steps.meta.outputs.tags }}