name: Release
on: push

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.20.0'

      - name: Build Binaries
        run: |
          mkdir -p builds/compressed
          go install github.com/mitchellh/gox@latest
          cd cmd/dss
          gox --output "../../builds/dss-{{.OS}}-{{.Arch}}" -ldflags '-s -w' -osarch 'darwin/amd64 darwin/arm64 linux/amd64 linux/arm freebsd/amd64 windows/amd64'
          cd ../../builds
          find . -maxdepth 1 -type f -execdir zip 'compressed/{}.zip' '{}' \;
      - name: Upload Binaries
        run: |
          go install github.com/tcnksm/ghr@latest
          ghr -t ${{ secrets.GITHUB_TOKEN }} --delete Latest builds/compressed/